apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-01
  namespace: pai-gpu
  annotations:
    start-time: '110.000'
    end-time: '900.000'
spec:
    containers:
    - image: tensorflow:latest
      name: main
      resources:
        limits:
          cpu: 8
          memory: 17408Mi
        requests:
          cpu: 8
          memory: 17408Mi
